> 지금까지는 pipeline을 받아서 tokenizer와 model을 그대로 썼는데, 이제는 fine tuning을 위해서 필요에 따라 tokenizer와 model의 구조를 파악하여 원하는 모델 등을 직접 받아오는 것.

# Transformers 를 이용해 Backbone 사용

## Transformers 설치
- `pip install transformers`

### Tokenizer, Model Loading
- Huggingface 모델 허브에서 제공하는 처리 모델을 다운받아 로딩한다.
- 다운로드된 모델은 `사용자 home 디렉토리\.cache\huggingface` 에 저장된다.
- 미리 학습된 언어 모델을 다운받아 사용할 때는 그 언어모델이 사용한 tokenizer를 같이 받아서 사용한다.

### [Auto Classes](https://huggingface.co/docs/transformers/model_doc/auto)
- Huggingface 에서 제공하는 다양한 모델들은 손쉽게 불러오고 사용할 수 있도록 설계된 유틸리티 클래스들을 말한다.
- 미리 학습된 특정 모델의 이름(모델 허브상에서 제공되는 이름)이나 저장된 local 경로를 제공하면 해당 모델에 맞는 적절한 클래스와 구성 요소를 자동으로 로드한다.
- 사용자는 모델을 사용하기 위한 정확한 클래스를 몰라도 쉽게 다양한 종류의 모델을 사용할 수있다.
> - 모델의 class를 잘 모르더라도 huggingface에서 알아서 찾아주도록하는 class

#### 주요 Auto Class
- 기본 모델 Loading - feature 추출기를 로드
    1. **AutoModel**
       - 주어진 모델 이름에 맞는 사전 학습된 모델을 자동으로 로드한다.
       - 예: `AutoModel.from_pretrained("bert-base-uncased")`: BERT 모델을 로드한다.
    2. **AutoTokenizer**
       - 해당 모델에 적합한 토크나이저를 자동으로 로드한다.
       - 예: `AutoTokenizer.from_pretrained("bert-base-uncased")`: BERT 모델에 맞는 토크나이저를 로드한다.
	   	> - 즉, 그 모델에서 쓰인 토크나이저가 쓰여야하므로 모델과 토크나이저의 ID는 같을 것.
    3. **AutoConfig**
       - 모델의 설정(config)을 자동으로 로드한다. 모델 설정에는 모델의 하이퍼파라미터와 모델 구조 정보가 포함된다. 이 설정을 이용해 모델을 생성할 수있다.
       - 예: `AutoConfig.from_pretrained("bert-base-uncased")`
- Task 처리 모델 Loading
    - Pretrained backbone 모델에 각 task 에 맞는 estimator layer를 추가한 모델을 생성해 제공한다.
	> - 형식: AutoModelFor[task]
    - 주요 모델들
        1. **AutoModelForSequenceClassification**
           - 시퀀스(Text) 분류 작업을 위한 모델을 자동으로 로드한다.
           - 예: `AutoModelForSequenceClassification.from_pretrained("bert-base-uncased")`
        2. **AutoModelForQuestionAnswering**
           - 질문-응답 작업을 위한 모델을 자동으로 로드한다.
           - 예: `AutoModelForQuestionAnswering.from_pretrained("bert-base-uncased")`
        3. **AutoModelForTokenClassification**
           - 토큰 분류 작업(예: 개체명 인식)을 위한 모델을 자동으로 로드한다.
           - 예: `AutoModelForTokenClassification.from_pretrained("bert-base-uncased")`

In [2]:
from transformers import AutoModel, AutoTokenizer, AutoConfig

In [8]:
# model_id = "bert-base-uncased" # 아래의 gpt2와 번갈아보며 확인해보자
model_id = "gpt2"

tokenizer = AutoTokenizer.from_pretrained(model_id)
print(type(tokenizer))
model = AutoModel.from_pretrained(model_id)
print(type(model))
config = AutoConfig.from_pretrained(model_id)
print(type(config))

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

c:\Users\Playdata\AppData\Local\miniconda3\envs\dl\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Playdata\.cache\huggingface\hub\models--gpt2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

<class 'transformers.models.gpt2.tokenization_gpt2_fast.GPT2TokenizerFast'>


Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

<class 'transformers.models.gpt2.modeling_gpt2.GPT2Model'>
<class 'transformers.models.gpt2.configuration_gpt2.GPT2Config'>


In [11]:
raw_txt = "I am a boy."
token = tokenizer(
	raw_txt,
	return_tensors="pt" # 토큰화 결과: default-list, "pt"-torch.tensor, "tf"-tensorflow.tensor, "np"-np.ndarray
	)

token

# input_ids: 토큰 id
# attention_mask: input_ids의 각 토큰들이 실제 토큰인지 [PAD] 토큰인지 여부. 1:유효(실제) 문자열 토큰, 0: [PAD]

{'input_ids': tensor([[  40,  716,  257, 2933,   13]]), 'attention_mask': tensor([[1, 1, 1, 1, 1]])}

In [12]:
type(token['input_ids'])

torch.Tensor

In [ ]:
# model
context_vector = model(**token) # 가변인자. 위 token의 리턴값 >>> {'input_ids': tensor([[  40,  716,  257, 2933,   13]]), 'attention_mask': tensor([[1, 1, 1, 1, 1]])}
								# 위의 dictionary를 풀어서 모델로 넣어주는 것. 그 결과로 context_vector가 나온다.

In [16]:
context_vector.last_hidden_state.shape
# 출력 : [1, 5, 768] >>> [1:문서(I am a boy.) 개수, 5: 토큰 수, 768: embedding vector의 차원수]

torch.Size([1, 5, 768])

In [17]:
# context_vector.past_key_values[0]

((tensor([[[[-1.5577e+00,  2.0585e+00,  1.3060e+00,  ..., -1.3825e+00,
             -6.3336e-01,  1.2624e+00],
            [-2.3259e+00,  2.3836e+00,  2.5165e+00,  ..., -1.5535e+00,
             -1.2954e+00,  2.7215e+00],
            [-2.3145e+00,  2.7101e+00,  1.5073e+00,  ..., -5.7809e-01,
             -1.9292e+00,  2.2634e+00],
            [-2.1507e+00,  3.1127e+00,  1.1419e+00,  ..., -1.6848e+00,
             -1.2933e+00,  2.2668e+00],
            [-2.3745e+00,  2.8471e+00,  2.0649e+00,  ..., -6.8010e-02,
             -1.9713e+00,  1.6389e+00]],
  
           [[-1.1913e-01, -4.7022e-01, -1.8900e+00,  ..., -6.0264e-01,
              1.1491e+00,  9.6728e-02],
            [ 8.0233e-01, -2.1909e+00, -2.6815e+00,  ..., -1.9200e+00,
              2.8771e+00,  4.0363e-01],
            [-7.1399e-01, -1.6105e+00, -2.9748e+00,  ..., -1.6920e+00,
              4.4462e+00,  1.8922e-01],
            [ 5.1423e-02, -1.3008e+00, -1.0734e+00,  ..., -4.3873e-01,
              2.9660e+00, -1.7707e+00

In [19]:
# tokenizer
t = tokenizer.encode("I am a boy.") # token id들만 리턴. 모델에 넣을땐 그냥 tokenizer("I am a boy.") 로 넣어야함
t

[40, 716, 257, 2933, 13]

In [20]:
tokenizer.decode(t)

'I am a boy.'

In [27]:
# 개별 토큰 확인
tokenizer.convert_tokens_to_ids("am")
tokenizer.convert_tokens_to_ids(["I","am","a","boy","나는"])

[40, 321, 64, 7081, 50256]

In [29]:
tokenizer.convert_ids_to_tokens(321)
tokenizer.convert_ids_to_tokens([40, 321, 64, 7081, 50256])
# <|endoftext|> : unknown token에 대한 특수 토큰

['I', 'am', 'a', 'boy', '<|endoftext|>']

## kcbert
- BERT 모델을 한글 텍스트로 학습 시킨 Pretrained model.
    - BERT는 Transformer의 Encoder 부분을 이용해 구현된 언어모델
    - https://arxiv.org/abs/1810.04805 
- https://huggingface.co/beomi/kcbert-base

### 토크나이저 모델 load

In [31]:
from transformers import AutoModel, AutoTokenizer

model_id = "beomi/kcbert-base"
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModel.from_pretrained(model_id)

In [32]:
model # bert모델과 구조는 같다. 단지 한국어 학습을 시킨 것 뿐.

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30000, 768, padding_idx=0)
    (position_embeddings): Embedding(300, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False

### 입력값 토큰화

In [41]:
sentences = [
	"안녕",
    "Hugging Face는 인공지능(AI)과 자연어 처리(NLP) 분야에서 혁신적인 도구와 모델을 제공하는 AI 스타트업이다.",
    "2016년에 설립된 이 회사는 주로 오픈소스 라이브러리와 사전 학습된 NLP 모델을 제공을 제공한다."
]

In [42]:
token = tokenizer(sentences[0])
token

{'input_ids': [2, 19017, 3], 'token_type_ids': [0, 0, 0], 'attention_mask': [1, 1, 1]}

In [43]:
token.keys()
# 위에서 gpt2와는 달리 'token_type_ids'가 추가됨
# 모델마다 return값이 조금씩 다르지만, 'input_ids', 'attention_mask' 이 두개는 무조건 있다.
# input_ids: 토큰 id들
# attention_mask: input_ids의 개별 토큰들이 실제 값인지 [PAD] 인지 구분.(1:실제토큰, 0:[PAD])
# token_type_id: 입력이 두개 문서로 구성된 경우(ex. question-answering처럼 Question, Context로 구성된 경우, 각 토큰이 몇번째 문서인지 구분하기 위한 값.
# 											즉, 어디까지 Question 토큰이고 어디서부터 Context 토큰인지!) >> 이하 예시 확인


### input_ids: 		[q,q,q,q,q,q,c,c,c,c,c,c] >> 예를 들어 이런 구성의 토큰이라면 아래와 같이 보여준다.
### token_type_ids: [0,0,0,0,0,0,1,1,1,1,1,1]

dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])

In [44]:
token['token_type_ids']

[0, 0, 0]

In [45]:
token_list = tokenizer(
	sentences,	  		# 토큰화할 문서들.
	max_length=10, 		# padding/truncation의 기준 길이 지정.
	padding=True,		# 패딩 추가. default: batch에서 가장 긴 sequence에 맞춰서 패딩.
				 		# max_length가 설정된 경우는 max_length에 맞춘다.
	truncation=True,	# max_length보다 개수가 많은 sequence일 경우 max_length에 맞춰 뒤에 토큰들을 잘라낸다.
	return_tensors="pt"
)

In [49]:
token_list["input_ids"] # 모두 첫 시작 토큰은 2, 마지막 토큰은 3. "안녕"의 토큰은 19017

tensor([[    2, 19017,     3,     0,     0,     0,     0,     0,     0,     0],
        [    2,    41,  4223,  4403,  4403, 18940,    39,  4243,  4773,     3],
        [    2, 26182,  4113, 20684,  4130,  2451, 22088, 20002, 15999,     3]])

In [50]:
token_list['attention_mask'] # >>>개별 토큰들이 실제 값인지 [PAD] 인지 구분.(1:실제토큰, 0:[PAD])

tensor([[1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [51]:
token_list['token_type_ids'] # 문서가 각각 문장 1개라서 모두 0이 나옴

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

### BERT 모델을 이용해 context vector 추출
#### Model 추론결과
- **last_hidden_state**
    - 모든 token들에 대한 feature
    - 출력이 **many**인 작업에 사용한다.
- **pooler_output**
    - 입력 문장, 텍스트에 대한 context vector 이다.
    - 이 값은 **문장을 입력받아 처리하는 task**(ex: 문서분류-감정분석,문장카테고리분류, 문장유사도 분석)의 입력으로 사용한다.

In [52]:
output = model(**token_list)

In [53]:
output.keys()

odict_keys(['last_hidden_state', 'pooler_output'])

In [54]:
output["pooler_output"].shape

torch.Size([3, 768])